format blame lines
lgewst/snu-helper-tool-project pull request #2
Opened 2022-03-21 12:10 UTC by fjvxmap

-b 옵션 사용 시 충돌이 일어나는 모든 파일들에 대해 git blame 커맨드를 적용하고 각 파일의 라인마다 rev, author_name, date, line_num, content 변수를 묶어 가지고 있게 됩니다.

2022-03-21 13:06 UTC, pasa3232 requested changes

2022-03-21 13:06 UTC, pasa3232 commented on sync-helper/__main__.py
> +    # file conflicts list
main pull 받아주세요. 최신 commit이 반영되지 않은 것 같습니다.

2022-03-21 13:07 UTC, pasa3232 commented
혹시 실행하면 얼마나 걸리나요?

2022-03-21 15:09 UTC, fjvxmap commented on sync-helper/__main__.py
> +    # file conflicts list
아하 알겠습니다!

2022-03-21 15:10 UTC, fjvxmap commented
> 혹시 실행하면 얼마나 걸리나요?

끝까지 실행해본 적이 없어서 모르겠습니다. 최소한 5분은 걸립니다.

2022-03-22 11:28 UTC, pasa3232 approved these changes
LGTM!

2022-03-23 14:05 UTC, merged